#!/bin/sh
#
# SPDX-License-Identifier: MIT
#
# Copyright (c) 2024 Christophe BLAESS, Alexandre GROSSET
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

opt_verbose=0
opt_dry_run=0
opt_init=/sbin/init

while [ "$1" != "" ]
do
	case "$1" in
		"-v" | "--verbose" ) opt_verbose=1 ;;
		"-n" | "--dry_run" ) opt_dry_run=1 ;;
		"-i" | "--init" )    shift; opt_init="$1" ;;
	esac
	shift
done

export PATH="/bin:/sbin:/usr/bin:/usr/sbin"

mount none /proc -t proc
mount none /sys  -t sysfs

for script in /etc/early-init.d/*
do
	if [ -x "${script}" ]
	then
		if [ ${opt_verbose} -gt 0 ]
		then
			echo "Running ${script}" >&2
		fi

		if [ ${opt_dry_run} -eq 0 ]
		then
			"${script}"
		fi
	fi
done

exec ${opt_init}
